/**
 * TCGPlayer CDN helpers for duel-web runtime stubs.
 * Product map is generated by `packages/rules` `npm run export-atlas`
 * (do not import @optcg/rules into the SPA).
 */
import productsJson from "../assets/tcgProducts.json";

type TcgProductHit = {
  productId: number;
  alts: { id: string; label: string; productId: number }[];
};

const TCG_PRODUCTS = productsJson as Record<string, TcgProductHit>;

export function tcgProductImageUrl(
  productId: number,
  size: "thumb" | "large" = "thumb",
): string {
  const suffix = size === "large" ? "_in_1000x1000" : "_400w";
  return `https://tcgplayer-cdn.tcgplayer.com/product/${productId}${suffix}.jpg`;
}

export function tcgArtForCard(cardId: string): string | undefined {
  const hit = TCG_PRODUCTS[cardId];
  return hit ? tcgProductImageUrl(hit.productId, "thumb") : undefined;
}

export function tcgAltsForCard(
  cardId: string,
): { id: string; label: string; imageUrl: string }[] {
  const hit = TCG_PRODUCTS[cardId];
  if (!hit?.alts?.length) return [];
  return hit.alts.map((a) => ({
    id: a.id,
    label: a.label,
    imageUrl: tcgProductImageUrl(a.productId, "thumb"),
  }));
}
