import { ABILITY_FULLALEAD_SEARCH, ABILITY_LAFFITTE_SEARCH, ABILITY_STAGE_TRASH_GIVE_RESTED_DON } from "../cards/abilityIds.js";
import { compileAbilityRegistry } from "./compiler.js";
import { ABILITY_SCHEMA_VERSION, type CardAbilityRecord } from "./schema.js";

export const ABILITY_MOBY_DICK_ON_PLAY = "op16_021_on_play_search";
export const ABILITY_MY_ERA_MAIN = "op09_096_main_search";
export const ABILITY_MY_ERA_TRIGGER = "op09_096_life_trigger";

const records: CardAbilityRecord[] = [
  { cardDefId: "OP12-112", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op12_112_life_draw", kind: "triggered", zones: ["life"], windows: ["life_trigger"], conditions: [{ type: "leader_is_multicolored" }], costs: [], operations: [{ type: "draw_cards", count: 2, player: "controller" }], implementation: "implemented", testRefs: ["drawPrograms:Life Trigger"] }] },
  { cardDefId: "OP16-108", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op16_108_life_draw", kind: "triggered", zones: ["life"], windows: ["life_trigger"], conditions: [], costs: [], operations: [{ type: "draw_cards", count: 2, player: "controller" }], implementation: "implemented", testRefs: ["drawPrograms:Life Trigger"] }] },
  { cardDefId: "ST01-004", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "st01_004_conditional_rush", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [{ type: "attached_don_at_least", count: 2 }], costs: [], operations: [{ type: "grant_keyword", keyword: "rush" }], implementation: "implemented", testRefs: ["modifiers:Sanji conditional Rush"] }] },
  { cardDefId: "ST01-005", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "jinbe_attack_power", kind: "triggered", zones: ["character"], windows: ["when_attacking"], conditions: [{ type: "attached_don_at_least", count: 1 }], costs: [], operations: [{ type: "choose_power_modifier", target: "friendly_leader_or_character", amount: 1000, duration: "turn", maxTargets: 1, excludeSource: true }], implementation: "implemented", testRefs: ["modifiers:Jinbe attack power"] }] },
  { cardDefId: "ST01-006", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "st01_006_blocker", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "grant_keyword", keyword: "blocker" }], implementation: "implemented", testRefs: ["engine:blocker"] }] },
  { cardDefId: "OP16-080", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op16_080_opponent_turn_field_cost", kind: "continuous", zones: ["leader"], windows: ["while_active"], conditions: [{ type: "opponent_turn" }], costs: [], operations: [{ type: "modify_field_cost", target: "friendly_characters", amount: 1, minimum: 0 }], implementation: "implemented", testRefs: ["playCost:Teach field cost"] }] },
  { cardDefId: "OP16-118", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op16_118_hand_counter_aura", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "replace_counter", target: "characters_in_hand", value: 2000, printedPower: 8000 }], implementation: "implemented", testRefs: ["modifiers:Ace counter aura"] }] },
  { cardDefId: "OP17-002", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op17_002_opponent_turn_power", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [{ type: "opponent_turn" }], costs: [], operations: [{ type: "modify_power", target: "source", amount: 3000 }], implementation: "implemented", testRefs: ["modifiers:Atmos"] }] },
  { cardDefId: "OP17-003", abilities: [
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: "op17_003_rush_character", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "grant_keyword", keyword: "rush_character" }], implementation: "implemented", testRefs: ["modifiers:Izo Rush Character"] },
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: "on_play_power_debuff", kind: "triggered", zones: ["character"], windows: ["on_play"], conditions: [{ type: "any", conditions: [{ type: "leader_has_name", names: ["Edward.Newgate"] }, { type: "leader_has_trait", trait: "Land of Wano" }] }], costs: [], operations: [{ type: "choose_power_modifier", target: "opponent_character", amount: -6000, duration: "turn", maxTargets: 1, restedOnly: true }], implementation: "implemented", testRefs: ["modifiers:Izo On Play"] },
  ] },
  { cardDefId: "OP17-005", abilities: [
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: "op17_005_hand_cost", kind: "continuous", zones: ["hand"], windows: ["while_active"], conditions: [{ type: "opponent_has_character_power_at_least", power: 10000 }], costs: [], operations: [{ type: "modify_play_cost", target: "source_in_hand", amount: -4, minimum: 0 }], implementation: "implemented", testRefs: ["playCost:Newgate"] },
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: "op17_005_on_play_leader_power", kind: "triggered", zones: ["character"], windows: ["on_play"], conditions: [{ type: "leader_is_monocolored" }], costs: [], operations: [{ type: "replace_base_power", target: "leader", power: 8000 }], implementation: "implemented", testRefs: ["playCost:Newgate leader base power"] },
  ] },
  { cardDefId: "OP17-008", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op17_008_on_play_leader_power", kind: "triggered", zones: ["character"], windows: ["on_play"], conditions: [{ type: "leader_has_name", names: ["Edward.Newgate"] }], costs: [], operations: [{ type: "replace_base_power", target: "leader", power: 8000 }], implementation: "implemented", testRefs: ["playCost:Jozu leader base power"] }] },
  { cardDefId: "ST23-001", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "st23_001_blocker", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "grant_keyword", keyword: "blocker" }], implementation: "implemented", testRefs: ["engine:blocker"] }, { schemaVersion: ABILITY_SCHEMA_VERSION, id: "st23_001_hand_cost", kind: "continuous", zones: ["hand"], windows: ["while_active"], conditions: [{ type: "controller_has_character_power_at_least", power: 10000 }], costs: [], operations: [{ type: "modify_play_cost", target: "source_in_hand", amount: -4, minimum: 0 }], implementation: "implemented", testRefs: ["playCost:Uta"] }] },
  { cardDefId: "EB04-058", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "eb04_058_blocker", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "grant_keyword", keyword: "blocker" }], implementation: "implemented", testRefs: ["engine:blocker"] }] },
  { cardDefId: "OP17-112", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op17_112_trigger_aura", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [{ type: "controller_turn" }], costs: [], operations: [{ type: "replace_base_power", target: "friendly_characters", power: 8000, printedPower: 4000, requiresTrigger: true }], implementation: "implemented", testRefs: ["modifiers:Linlin aura"] }] },
  { cardDefId: "OP09-086", abilities: [
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: "op09_086_trash_power", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [{ type: "leader_has_trait", trait: "Blackbeard Pirates" }], costs: [], operations: [{ type: "modify_power", target: "source", amount: 1000, perTrashCards: 4 }], implementation: "implemented", testRefs: ["modifiers:Burgess trash scaling"] },
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: "op09_086_effect_ko_immunity", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "prevent_effect_ko", target: "source" }], implementation: "implemented", testRefs: ["engine:Burgess immunity"] },
  ] },
  { cardDefId: "OP09-093", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op09_093_blocker", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "grant_keyword", keyword: "blocker" }], implementation: "implemented", testRefs: ["engine:blocker"] }] },
  { cardDefId: "OP09-118", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "op09_118_rush", kind: "continuous", zones: ["character"], windows: ["while_active"], conditions: [], costs: [], operations: [{ type: "grant_keyword", keyword: "rush" }], implementation: "implemented", testRefs: ["engine:Roger Rush"] }] },
  { cardDefId: "OP16-104", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "copy_opponent_power", kind: "triggered", zones: ["character"], windows: ["when_attacking"], conditions: [], costs: [], operations: [{ type: "copy_opponent_character_power", duration: "turn" }], implementation: "implemented", testRefs: ["engine:Catarina Devon attack ability"] }] },
  { cardDefId: "OP14-108", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: "on_play_ko_power", kind: "triggered", zones: ["character"], windows: ["on_play"], conditions: [{ type: "leader_is_multicolored" }, { type: "opponent_life_at_most", count: 3 }], costs: [], operations: [{ type: "choose_ko", target: "opponent_character", compare: "base_power", maxValue: 7000, maxTargets: 1 }], implementation: "implemented", testRefs: ["onPlayEffects:Rayleigh"] }] },
  { cardDefId: "OP09-095", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: ABILITY_LAFFITTE_SEARCH, kind: "activated", zones: ["character"], windows: ["activate_main"], conditions: [{ type: "source_is_active" }], costs: [{ type: "rest_don", count: 1 }, { type: "rest_source" }], operations: [{ type: "search_top_deck", count: 5, maxSelect: 1, selector: { traits: ["Blackbeard Pirates"] }, destination: "hand", remainder: "deck_bottom" }], implementation: "implemented", testRefs: ["searchEffects:Laffitte"] }] },
  { cardDefId: "OP09-099", abilities: [{ schemaVersion: ABILITY_SCHEMA_VERSION, id: ABILITY_FULLALEAD_SEARCH, kind: "activated", zones: ["stage"], windows: ["activate_main"], conditions: [{ type: "source_is_active" }], costs: [{ type: "trash_hand", count: 1 }, { type: "rest_source" }], operations: [{ type: "search_top_deck", count: 3, maxSelect: 1, selector: { traits: ["Blackbeard Pirates"] }, destination: "hand", remainder: "deck_bottom" }], implementation: "implemented", testRefs: ["searchEffects:Fullalead"] }] },
  { cardDefId: "OP16-021", abilities: [
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: ABILITY_MOBY_DICK_ON_PLAY, kind: "triggered", zones: ["stage"], windows: ["on_play"], conditions: [{ type: "leader_has_trait", trait: "Whitebeard Pirates" }], costs: [], operations: [{ type: "search_top_deck", count: 3, maxSelect: 1, destination: "hand", remainder: "deck_bottom" }], implementation: "implemented", testRefs: ["searchEffects:Moby Dick On Play"] },
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: ABILITY_STAGE_TRASH_GIVE_RESTED_DON, kind: "activated", zones: ["stage"], windows: ["activate_main"], conditions: [], costs: [{ type: "trash_source" }], operations: [{ type: "attach_rested_don", count: 1, target: "intent_target", optional: true }], implementation: "implemented", testRefs: ["engine:Moby Dick Stage Activate Main"] },
  ] },
  { cardDefId: "OP09-096", abilities: [
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: ABILITY_MY_ERA_MAIN, kind: "triggered", zones: ["hand", "trash"], windows: ["main"], conditions: [], costs: [], operations: [{ type: "search_top_deck", count: 3, maxSelect: 1, selector: { traits: ["Blackbeard Pirates"], excludeDefIds: ["OP09-096"] }, destination: "hand", remainder: "trash" }], implementation: "implemented", testRefs: ["searchEffects:My Era Main"] },
    { schemaVersion: ABILITY_SCHEMA_VERSION, id: ABILITY_MY_ERA_TRIGGER, kind: "triggered", zones: ["life"], windows: ["life_trigger"], conditions: [], costs: [], operations: [{ type: "invoke_ability", abilityId: ABILITY_MY_ERA_MAIN }], implementation: "implemented", testRefs: ["searchEffects:My Era Trigger"] },
  ] },
];

export const ABILITY_REGISTRY = compileAbilityRegistry(records);
export function abilitiesForCard(cardDefId: string) { return ABILITY_REGISTRY.cards.get(cardDefId)?.abilities ?? []; }
export function abilityForCard(cardDefId: string, abilityId: string) { const ability = ABILITY_REGISTRY.abilities.get(abilityId); return ability && ABILITY_REGISTRY.cards.get(cardDefId)?.abilities.includes(ability) ? ability : undefined; }

/** Printed unconditional keyword for catalog display; dynamic legality uses current conditions. */
export function hasUnconditionalKeyword(cardDefId: string, keyword: "blocker" | "rush"): boolean {
  return abilitiesForCard(cardDefId).some((ability) => ability.kind === "continuous" && ability.zones.includes("character") && ability.conditions.length === 0 && ability.operations.some((operation) => operation.type === "grant_keyword" && operation.keyword === keyword));
}
