/**
 * Reviewed, hand-authored ability definitions for printed text the offline
 * compiler cannot express. Two forms:
 *
 * - `{ abilities }` replaces the generated definition for the card entirely.
 * - `{ patch }` adds abilities to the generated definition. Each patch
 *   ability's `text` must be the start of one of the card's unsupported
 *   generated clauses; that clause is then treated as implemented. A patch that
 *   matches no unsupported clause fails registry validation, so patches go
 *   stale loudly when the grammar learns the clause.
 *
 * `drop` lists garbled fragments of bundled (non-Bandai) text that are covered
 * by a patch ability written from the full printed text.
 *
 * Every entry must stay plain JSON-compatible data; the helpers below only
 * build objects.
 */
import type { Ability, CardAbilities, Cond, Cost, Duration, Effect, Filter, Selector, Target, Value } from "../effects/types.js";

export type ManualEntry =
  | (Pick<CardAbilities, "abilities"> & Partial<Pick<CardAbilities, "unsupported" | "status">>)
  | { patch: Ability[]; drop?: string[] };

type Draft = Omit<Ability, "id">;

// ---------------------------------------------------------------------------
// Builders
// ---------------------------------------------------------------------------

const le = (value: Value) => ({ op: "<=" as const, value });
const ge = (value: Value) => ({ op: ">=" as const, value });
const eq = (value: Value) => ({ op: "==" as const, value });

const sel = (player: Selector["player"], zone: Selector["zone"], filter?: Filter, also?: Selector[]): Selector => ({ player, zone, ...(filter ? { filter } : {}), ...(also ? { also } : {}) });
const oppChar = (filter?: Filter) => sel("opponent", "character", filter);
const myChar = (filter?: Filter) => sel("you", "character", filter);
const oppDon = (filter?: Filter) => sel("opponent", "don", filter);
const oppCharOrDon = (filter?: Filter) => sel("opponent", "character", filter, [oppDon()]);
const myLeaderOrChar = (filter?: Filter) => sel("you", "leader_or_character", filter);

const upTo = (max: number, selector: Selector, extra: Partial<Extract<Target, { ref: "choose" }>> = {}): Target => ({ ref: "choose", selector, min: 0, max, ...extra });
const exactly = (n: number, selector: Selector, extra: Partial<Extract<Target, { ref: "choose" }>> = {}): Target => ({ ref: "choose", selector, min: n, max: n, ...extra });
const v = (name: string): Target => ({ ref: "var", name });
const self: Target = { ref: "self" };
const myLeader: Target = { ref: "leader", player: "you" };

const seq = (...steps: Effect[]): Effect => ({ do: "seq", steps });
const when = (cond: Cond, then: Effect, otherwise?: Effect): Effect => ({ do: "if", cond, then, ...(otherwise ? { else: otherwise } : {}) });
const may = (then: Effect, costs?: Cost[]): Effect => ({ do: "may", then, ...(costs ? { costs } : {}) });
const oneOf = (...options: [string, Effect][]): Effect => ({ do: "choose_one", options: options.map(([label, effect]) => ({ label, effect })) });
const select = (bind: string, selector: Selector, min: number, max: number, extra: Partial<Extract<Effect, { do: "select" }>> = {}): Effect => ({ do: "select", bind, selector, min, max, ...extra });
const power = (target: Target, amount: Value, duration: Duration = "turn"): Effect => ({ do: "power", target, amount, duration });
const ko = (target: Target): Effect => ({ do: "ko", target });
const rest = (target: Target): Effect => ({ do: "rest", target });
const play = (target: Target, rested = false): Effect => ({ do: "play", target, ...(rested ? { rested } : {}) });
const draw = (count: Value): Effect => ({ do: "draw", player: "you", count });
const discard = (count: Value, extra: Partial<Extract<Effect, { do: "discard" }>> = {}): Effect => ({ do: "discard", player: "you", count, ...extra });
const addDon = (count: number, rested: boolean): Effect => ({ do: "add_don", player: "you", count, rested });
const keyword = (target: Target, kw: Extract<Effect, { do: "keyword" }>["keyword"], duration: Duration = "turn"): Effect => ({ do: "keyword", target, keyword: kw, duration });
const restrict = (target: Target, restriction: Extract<Effect, { do: "restrict" }>["restriction"], duration: Duration = "turn", extra: { filter?: Filter } = {}): Effect => ({ do: "restrict", target, restriction, duration, ...extra });
/** `reveal` must match the printed text ("reveal up to …"); an unrevealed look is private to its player. */
const look = (count: number, pick: Filter | null, max: number, reveal: boolean, rest: Extract<Effect, { do: "look" }>["rest"] = "deck_bottom"): Effect => ({ do: "look", player: "you", count, picks: [{ ...(pick ? { filter: pick } : {}), min: 0, max, dest: "hand" }], rest, reveal });
const giveDonChoice = (donState: "rested" | "any"): Effect => oneOf(
  ["Give your DON!! card to your Leader or Character", { do: "give_don", target: exactly(1, myLeaderOrChar()), count: 1, donState, player: "you" }],
  ["Give your opponent's DON!! card to their Leader or Character", { do: "give_don", target: exactly(1, sel("opponent", "leader_or_character")), count: 1, donState, player: "opponent" }],
);
/** "Choose a cost and reveal 1 card from the top of your opponent's deck. If the revealed card has the chosen cost, …" */
const guessCost = (then: Effect): Effect => seq(
  { do: "choose_number", bind: "_n", max: 10, prompt: "choose a cost" },
  { do: "reveal_top", player: "opponent", bind: "_rev" },
  when({ c: "var_any_match", name: "_rev", filter: { cost: eq({ count: { of: "var", name: "_n" } }) } }, then),
);

const exists = (selector: Selector, atLeast?: number): Cond => ({ c: "exists", selector, ...(atLeast ? { atLeast } : {}) });
const none = (selector: Selector): Cond => ({ c: "none", selector });
const cmp = (left: Value, op: Extract<Cond, { c: "compare" }>["op"], right: Value): Cond => ({ c: "compare", left, op, right });
const leaderName = (...names: string[]): Cond => ({ c: "leader_name", names });
const leaderTrait = (...traits: string[]): Cond => ({ c: "leader_trait", traits });
const leaderTraitIncludes = (text: string): Cond => ({ c: "leader_trait_includes", text });
const count = (selector: Selector): Value => ({ count: { of: "cards", selector } });
const trashCount: Value = { count: { of: "trash", player: "you" } };
const lifeCount: Value = { count: { of: "life", player: "you" } };
const donField = (player: "you" | "opponent"): Value => ({ count: { of: "don_field", player } });

const CHAR: Filter = { types: ["character"] };
const WB = "Whitebeard Pirates";

function card(id: string, patch: Draft[], drop?: string[]): [string, ManualEntry] {
  return [id, { patch: patch.map((a, i) => ({ id: `${id.toLowerCase()}#m${i}`, ...a })), ...(drop ? { drop } : {}) }];
}

// ---------------------------------------------------------------------------
// Entries
// ---------------------------------------------------------------------------

const ENTRIES: [string, ManualEntry][] = [
  card("EB01-020", [{ trigger: "main", text: "[Main] If your Leader has the {Supernovas} type, return 1 of your Characters",
    effect: when(leaderTrait("Supernovas"), seq(
      { do: "to_hand", target: exactly(1, myChar(), { bind: "_ret" }) },
      play(upTo(1, sel("you", "hand", { ...CHAR, cost: le(2), notColorsOfVar: "_ret" }))),
    )) }]),
  card("EB01-030", [{ trigger: "activate_main", text: "[Activate: Main] You may place this card and 1 card from your hand",
    costs: [{ k: "hand_to_deck_bottom", count: 1 }, { k: "self_to_deck_bottom" }], effect: draw(2) }]),
  card("EB02-009", [{ trigger: "activate_main", text: "[Activate: Main] You may rest this Stage: Give up to 1 of your currently given DON!!",
    costs: [{ k: "rest_self" }],
    effect: { do: "move_don", from: upTo(1, myLeaderOrChar({ donGiven: ge(1) })), to: exactly(1, myChar({ traits: ["Straw Hat Crew"] })), count: 1 } }]),
  card("EB02-030", [
    { trigger: "counter", text: "[Counter] If any of your Characters would be KO'd in battle during this turn", effect: { do: "grant", ability: "m1", duration: "turn" } },
    { trigger: "replacement", text: "[Counter] If any of your Characters would be KO'd in battle during this turn",
      replacement: { event: "ko_in_battle", target: myChar(), instead: { do: "pay", costs: [{ k: "trash_hand", count: 1 }], then: { do: "nothing" } }, optional: true } },
  ]),
  card("EB02-035", [{ trigger: "on_event", oncePerTurn: true, text: "[Your Turn] [Once Per Turn] When 2 or more DON!! cards",
    eventTrigger: { event: "don_returned", player: "you", minCount: 2 }, conditions: [{ c: "your_turn" }], effect: addDon(1, false) }]),
  card("EB02-039", [{ trigger: "main", text: "[Main] You may trash 1 {GERMA 66} type Character card",
    costs: [{ k: "trash_hand", count: 1, filter: { ...CHAR, traits: ["GERMA 66"], power: le(4000) } }],
    effect: when(cmp(donField("you"), "<=", donField("opponent")),
      play(upTo(1, sel("you", "trash", { ...CHAR, all: [{ power: ge(5000) }, { power: le(7000) }], sameNameAsVar: "_cost" })))) }]),
  card("EB03-012", [{ trigger: "activate_main", text: "[Activate: Main] You may rest this Character: Rest up to 1 of your opponent's DON!!",
    costs: [{ k: "rest_self" }], effect: rest(upTo(1, oppCharOrDon({ traits: ["Animal", "SMILE"], cost: le(3) }))) }]),
  card("EB03-042", [{ trigger: "on_ko", text: "[Opponent's Turn] [On KO] Play up to 1 {Revolutionary Army}", conditions: [{ c: "opponent_turn" }],
    effect: play(upTo(1, sel("you", "hand_or_trash", { ...CHAR, cost: le(6), any: [{ traits: ["Revolutionary Army"], notNames: ["Koala"] }, { names: ["Nico Robin"] }] }))) }]),
  card("EB03-049", [{ trigger: "main", text: "[Main] You may rest 7 of your DON!! cards: If your Leader is [Perona]",
    costs: [{ k: "rest_don", count: 7 }],
    effect: when(leaderName("Perona"), seq(
      play(upTo(1, sel("you", "hand_or_trash", { ...CHAR, traits: ["Thriller Bark Pirates"], cost: le(6) }))),
      play(upTo(1, sel("you", "hand_or_trash", { ...CHAR, traits: ["Thriller Bark Pirates"], cost: le(4) }))),
    )) }]),
  card("EB03-061", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] Set up to 1 of your DON!! cards as active. Then, rest",
    effect: seq({ do: "set_don_active", count: 1 }, rest(upTo(1, oppCharOrDon({ cost: le(4) })))) }]),
  card("EB04-011", [{ trigger: "on_play", text: "[On Play] Draw a card for each of your {Neptunian}",
    effect: seq(draw(count(myChar({ traits: ["Neptunian"] }))), discard(count(myChar({ traits: ["Neptunian"] })))) }]),
  card("EB04-044", [{ trigger: "replacement", oncePerTurn: true, text: "[Once Per Turn] If your Leader's type includes \"Navy\" and this Character would be removed",
    conditions: [leaderTraitIncludes("Navy")],
    replacement: { event: "removed", target: "self", instead: { do: "pay", costs: [{ k: "trash_hand", count: 1 }], then: { do: "nothing" } }, optional: true } }]),
  card("OP01-002", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] [RDON 2] If you have 5 Characters",
    costs: [{ k: "rest_don", count: 2 }],
    effect: when(exists(myChar(), 5), seq(
      { do: "to_hand", target: exactly(1, myChar(), { bind: "_ret" }) },
      play(upTo(1, sel("you", "hand", { ...CHAR, cost: le(5), notColorsOfVar: "_ret" }))),
    )) }]),
  card("OP01-051", [{ trigger: "static", don: 1, text: "[DON!! x1] [Opponent's Turn] If this Character is rested",
    conditions: [{ c: "opponent_turn" }, { c: "self_rested", value: true }],
    statics: [{ s: "player_restrict", player: "opponent", restriction: "attack_only_matching", filter: { ...CHAR, names: ["Eustass\"Captain\"Kid"] } }] }]),
  card("OP01-062", [{ trigger: "on_event", don: 1, oncePerTurn: true, text: "[DON!! x1] When you activate an Event, you may draw 1 card",
    eventTrigger: { event: "event_activated", player: "you" }, conditions: [cmp({ count: { of: "hand", player: "you" } }, "<=", 4)],
    effect: may(draw(1)) }]),
  card("OP01-063", [{ trigger: "activate_main", don: 1, text: "[DON!! x1] [Activate: Main] You may rest this Character: Choose 1 card from your opponent's hand",
    costs: [{ k: "rest_self" }],
    effect: seq(
      select("_rev", sel("opponent", "hand"), 1, 1, { random: true }),
      { do: "reveal", target: v("_rev") },
      when({ c: "var_any_match", name: "_rev", filter: { types: ["event"] } }, { do: "to_deck", target: upTo(1, sel("opponent", "life")), position: "bottom" }),
    ) }]),
  card("OP03-001", [{ trigger: "on_event", text: "When this Leader attacks or is attacked",
    eventTrigger: { event: "attack_declared", player: "you", filter: { types: ["leader"] }, alsoEvents: ["self_attacked"] },
    conditions: [{ c: "or", conds: [{ c: "attacker_is_self" }, { c: "self_is_battle_target" }] }],
    effect: seq(
      select("_t", sel("you", "hand", { types: ["event", "stage"] }), 0, 60),
      { do: "to_trash", target: v("_t") },
      power(self, { count: { of: "var", name: "_t" }, times: 1000 }, "battle"),
    ) }]),
  card("OP03-027", [{ trigger: "on_play", text: "[On Play] If your Leader has the {East Blue} type, rest up to 1",
    effect: when(leaderTrait("East Blue"), seq(
      rest(upTo(1, oppChar({ cost: le(2) }))),
      when(none(myChar({ names: ["Buchi"] })), play(upTo(1, sel("you", "hand", { names: ["Buchi"] })))),
    )) }]),
  card("OP03-096", [{ trigger: "main", text: "[Main] KO up to 1 of your opponent's Characters with a cost of 0",
    effect: ko(upTo(1, sel("opponent", "character", { cost: eq(0) }, [sel("opponent", "stage", { cost: le(3) })]))) }]),
  card("OP04-040", [{ trigger: "when_attacking", don: 1, text: "[DON!! x1] [When Attacking] If you have a total of 4 or less",
    effect: when(cmp({ count: { of: "sum", exprs: [{ of: "life", player: "you" }, { of: "hand", player: "you" }] } }, "<=", 4),
      when(exists(myChar({ cost: ge(8) })),
        oneOf(["Draw 1 card", draw(1)], ["Add the top card of your deck to the top of your Life cards", { do: "deck_to_life", player: "you", count: 1 }]),
        draw(1))) }]),
  card("OP04-047", [{ trigger: "on_event", text: "[Your Turn] At the end of a battle in which this Character battles",
    eventTrigger: { event: "battle_ended_vs_character", player: "you" }, conditions: [{ c: "your_turn" }],
    effect: when({ c: "battle_opponent", filter: { ...CHAR, cost: le(5) } }, { do: "to_deck", target: { ref: "battle", role: "opponent_battler" }, position: "bottom" }) }]),
  card("OP04-082", [{ trigger: "replacement", text: "If this Character would be KO'd, you may rest your Leader or 1 [Corrida Coliseum]",
    replacement: { event: "ko", target: "self", instead: { do: "pay", costs: [{ k: "rest_cards", selector: sel("you", "leader", undefined, [sel("you", "stage", { names: ["Corrida Coliseum"] })]), count: 1 }], then: { do: "nothing" } }, optional: true } }]),
  card("OP04-094", [{ trigger: "main", text: "[Main] Choose up to 1 of your opponent's Characters with a cost of 4 or less and KO it.",
    effect: when(cmp(trashCount, ">=", 15), ko(upTo(1, oppChar({ cost: le(6) }))), ko(upTo(1, oppChar({ cost: le(4) })))) }]),
  card("OP05-001", [{ trigger: "replacement", don: 1, oncePerTurn: true, text: "[DON!! x1] [Opponent's Turn] [Once Per Turn] If your Character with 5000 power",
    conditions: [{ c: "opponent_turn" }],
    replacement: { event: "ko", target: myChar({ power: ge(5000) }), instead: power(v("_target"), -1000), optional: true } }]),
  card("OP05-002", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may trash 1 {Revolutionary Army}",
    costs: [{ k: "trash_hand", count: 1, filter: { traits: ["Revolutionary Army"] } }],
    effect: power(upTo(3, myChar({ any: [{ traits: ["Revolutionary Army"] }, { hasTrigger: true }] })), 3000) }]),
  card("OP05-040", [{ trigger: "static", text: "If your Leader is [Donquixote Doflamingo], all Characters with a cost of 5 or less",
    conditions: [leaderName("Donquixote Doflamingo")],
    statics: [{ s: "restrict", target: { all: sel("any", "character", { cost: le(5) }) }, restriction: "no_refresh" }] }]),
  card("OP05-053", [{ trigger: "on_event", oncePerTurn: true, text: "[Your Turn] [Once Per Turn] When you draw a card outside",
    eventTrigger: { event: "card_drawn_by_effect", player: "you" }, conditions: [{ c: "your_turn" }], effect: power(self, 2000) }]),
  card("OP05-094", [{ trigger: "main", text: "[Main] Give up to 1 of your opponent's Characters -3 cost",
    effect: seq({ do: "cost", target: upTo(1, oppChar()), amount: -3, duration: "turn" }, restrict(upTo(1, oppChar({ cost: eq(0) })), "no_refresh", "permanent")) }]),
  card("OP05-096", [
    { trigger: "main", text: "[Main] Choose one: • KO up to 1 of your opponent's Characters with a cost of 1 or less.",
      effect: seq(
        oneOf(
          ["KO up to 1 of your opponent's Characters with a cost of 1 or less", ko(upTo(1, oppChar({ cost: le(1) })))],
          ["Return up to 1 of your opponent's Characters with a cost of 1 or less to the owner's hand", { do: "to_hand", target: upTo(1, oppChar({ cost: le(1) })) }],
          ["Place up to 1 of your opponent's Characters with a cost of 1 or less at the top or bottom of their Life cards face-up", { do: "to_life", target: upTo(1, oppChar({ cost: le(1) })), position: "top_or_bottom", faceUp: true }],
        ),
        when(exists(myChar({ traits: ["Celestial Dragons"] })), draw(1)),
      ) },
    { trigger: "trigger", text: "[Trigger] KO up to 1 of your opponent's Characters with a cost of 6 or less, or return",
      effect: seq(select("_t", oppChar({ cost: le(6) }), 0, 1), oneOf(["K.O. it", ko(v("_t"))], ["Return it to the owner's hand", { do: "to_hand", target: v("_t") }])) },
  ]),
  card("OP05-098", [{ trigger: "on_event", oncePerTurn: true, text: "[Opponent's Turn] [Once Per Turn] When your number of Life cards becomes 0",
    eventTrigger: { event: "life_removed", player: "you" }, conditions: [{ c: "opponent_turn" }, cmp(lifeCount, "==", 0)],
    effect: seq({ do: "deck_to_life", player: "you", count: 1 }, discard(1)) }]),
  card("OP05-100", [{ trigger: "replacement", oncePerTurn: true, text: "[Once Per Turn] If this Character would leave the field",
    conditions: [none(sel("any", "character", { names: ["Monkey.D.Luffy"] }))],
    replacement: { event: "removed", target: "self", instead: { do: "pay", costs: [{ k: "trash_life", count: 1 }], then: { do: "nothing" } }, optional: true } }]),
  card("OP06-020", [{ trigger: "activate_main", text: "[Activate: Main] You may rest this Leader: Rest up to 1 of your opponent's DON!!",
    costs: [{ k: "rest_self" }],
    effect: seq(rest(upTo(1, oppCharOrDon({ cost: le(3) }))), { do: "player_restrict", player: "you", restriction: "cannot_add_life_to_hand_by_effect", duration: "turn" }) }]),
  card("OP06-033", [{ trigger: "on_play", text: "[On Play] You may trash 1 {Fish-Man} type card from your hand or 1 [The Ark Noah]",
    costs: [{ k: "trash_cards", selector: sel("you", "hand", { any: [{ traits: ["Fish-Man"] }, { names: ["The Ark Noah"] }] }, [sel("you", "stage", { names: ["The Ark Noah"] })]), count: 1 }],
    effect: ko(upTo(1, oppChar({ rested: true }))) }]),
  card("OP06-035", [{ trigger: "on_play", text: "[On Play] Rest up to a total of 2 of your opponent's Characters or DON!!",
    effect: seq(rest(upTo(2, oppCharOrDon())), { do: "life_to_hand", player: "you", count: 1, position: "top" }) }]),
  card("OP06-048", [{ trigger: "on_event", text: "[Your Turn] When your opponent activates [Blocker] or an Event",
    eventTrigger: { event: "blocker_activated", player: "opponent", alsoEvents: ["event_activated"] }, conditions: [{ c: "your_turn" }, leaderTrait("East Blue")],
    effect: may({ do: "mill", player: "you", count: 4 }) }]),
  card("OP06-086", [{ trigger: "on_play", text: "[On Play] Choose up to 1 Character card with a cost of 4 or less and up to 1",
    effect: seq(
      select("_a", sel("you", "trash", { ...CHAR, cost: le(4) }), 0, 1),
      select("_b", sel("you", "trash", { ...CHAR, cost: le(2), excludeVar: "_a" }), 0, 1),
      oneOf(["Play the first card active and the second rested", seq(play(v("_a")), play(v("_b"), true))], ["Play the second card active and the first rested", seq(play(v("_b")), play(v("_a"), true))]),
    ) }]),
  card("OP06-095", ["main", "counter"].map((trigger) => ({ trigger: trigger as "main" | "counter", text: "[Main]/[Counter] Your Leader gains +1000 power during this turn.",
    effect: seq(
      power(myLeader, 1000),
      select("_k", myChar({ traits: ["Thriller Bark Pirates"], cost: le(2) }), 0, 5),
      ko(v("_k")),
      power(myLeader, { count: { of: "var", name: "_affected" }, times: 1000 }),
    ) }))),
  card("OP07-001", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] Give up to 2 total of your currently given DON!!",
    effect: { do: "move_don", from: upTo(2, myLeaderOrChar({ donGiven: ge(1) })), to: exactly(1, myChar()), count: 2 } }]),
  card("OP07-026", [{ trigger: "on_play", text: "[On Play] Up to 1 of your opponent's rested Character or DON!!",
    effect: restrict(upTo(1, sel("opponent", "character", { rested: true }, [oppDon({ rested: true })])), "no_refresh", "permanent") }]),
  card("OP07-031", [{ trigger: "on_event", oncePerTurn: true, text: "[Your Turn] [Once Per Turn] If a Character is rested by your effect",
    eventTrigger: { event: "character_rested", player: "any", byYourEffect: true }, conditions: [{ c: "your_turn" }], effect: seq(draw(1), discard(1)) }]),
  card("OP07-042", [{ trigger: "replacement", oncePerTurn: true, text: "[Once Per Turn] If your Leader has the {The Seven Warlords of the Sea} type",
    conditions: [leaderTrait("The Seven Warlords of the Sea")],
    replacement: { event: "removed_by_opponent_effect", target: "self", byOpponent: true, instead: { do: "pay", costs: [{ k: "cards_to_deck_bottom", selector: myChar({ notNames: ["Gecko Moria"] }), count: 1 }], then: { do: "nothing" } }, optional: true } }]),
  card("OP07-059", [{ trigger: "when_attacking", text: "[When Attacking] DON!! -3: If you have 3 or more {Foxy Pirates}",
    costs: [{ k: "return_don", count: 3 }],
    effect: when(exists(myChar({ traits: ["Foxy Pirates"] }), 3), seq(
      restrict({ ref: "all", selector: sel("opponent", "leader", { rested: true }) }, "no_refresh", "permanent"),
      restrict(upTo(1, oppChar()), "no_refresh", "permanent"),
    )) }]),
  card("OP07-075", [{ trigger: "counter", text: "[Counter] DON!! -1: Give up to 1 each of your opponent's Leader and Character",
    costs: [{ k: "return_don", count: 1 }],
    effect: seq(power(upTo(1, sel("opponent", "leader")), -2000), power(upTo(1, oppChar()), -2000)) }]),
  card("OP07-091", [{ trigger: "when_attacking", text: "[When Attacking] Trash up to 1 of your opponent's Characters with a cost of 2 or less.",
    effect: seq(
      { do: "to_trash", target: upTo(1, oppChar({ cost: le(2) })) },
      select("_p", sel("you", "trash", { ...CHAR, cost: ge(4) }), 0, 60),
      { do: "to_deck", target: v("_p"), position: "bottom" },
      power(self, { count: { of: "var", name: "_p" }, per: 3, times: 1000 }),
    ) }]),
  card("OP07-097", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] [RDON 1] Select up to 1 {Egghead}",
    costs: [{ k: "rest_don", count: 1 }],
    effect: seq(select("_s", sel("you", "hand", { traits: ["Egghead"], cost: le(5) }), 0, 1),
      oneOf(["Play it", play(v("_s"))], ["Add it to the top of your Life cards face-up", { do: "to_life", target: v("_s"), position: "top", faceUp: true }])) }]),
  card("OP08-043", [{ trigger: "on_play", text: "[On Play] If your Leader's type includes \"Whitebeard Pirates\" and you have 2 or less Life cards",
    effect: when({ c: "and", conds: [leaderTraitIncludes(WB), cmp(lifeCount, "<=", 2)] },
      { do: "restrict", target: { ref: "all", selector: oppChar() }, restriction: "attack_requires_discard", value: 2, duration: "until_end_of_opponent_next_turn" }) }]),
  card("OP08-053", [{ trigger: "main", text: "[Main] If your Leader's type includes \"Whitebeard Pirates\", look at 3",
    effect: when(leaderTraitIncludes(WB), look(3, { any: [{ traitIncludes: [WB] }, { names: ["Monkey.D.Luffy"] }] }, 1, true, "top_or_bottom")) }]),
  card("OP08-062", [{ trigger: "activate_main", text: "[Activate: Main] You may trash this Character: If your Leader has the {Big Mom Pirates}",
    costs: [{ k: "trash_self" }],
    effect: when(leaderTrait("Big Mom Pirates"), play(upTo(1, sel("you", "hand", { names: ["Charlotte Katakuri"], all: [{ cost: ge(3) }, { cost: le(donField("opponent")) }] })))) }]),
  card("OP08-074", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] If you have no other [Black Maria]",
    effect: when(none(myChar({ names: ["Black Maria"], excludeSelf: true })), seq(
      addDon(5, true),
      { do: "delay", when: "end_of_turn", effect: { do: "return_don", player: "you", count: { count: { of: "diff", left: { of: "don_field", player: "you" }, right: { of: "don_field", player: "opponent" } } } } },
    )) }]),
  card("OP08-098", [{ trigger: "when_attacking", don: 1, text: "[DON!! x1] [When Attacking] Play up to 1 {Shandian Warrior}",
    effect: seq(play(upTo(1, sel("you", "hand", { ...CHAR, traits: ["Shandian Warrior"], cost: le(donField("you")) }))),
      when({ c: "var_count", name: "_affected", op: ">=", value: 1 }, { do: "life_to_hand", player: "you", count: 1, position: "top" })) }]),
  card("OP08-118", [{ trigger: "on_play", text: "[On Play] Select up to 2 of your opponent's Characters, and give 1 Character -3000",
    effect: seq(
      power(upTo(1, oppChar(), { bind: "_a" }), -3000, "until_end_of_opponent_next_turn"),
      power(upTo(1, oppChar({ excludeVar: "_a" })), -2000, "until_end_of_opponent_next_turn"),
      ko(upTo(1, oppChar({ power: le(3000) }))),
    ) }]),
  card("OP09-012", [{ trigger: "replacement", text: "If your Character [Bonk Punch] would be KO'd by an effect",
    replacement: { event: "ko_by_effect", target: myChar({ names: ["Bonk Punch"] }), instead: { do: "pay", costs: [{ k: "trash_self" }], then: { do: "nothing" } }, optional: true } }]),
  card("OP09-022", [{ trigger: "static", text: "Your Character cards are played rested.",
    statics: [{ s: "player_restrict", player: "you", restriction: "characters_played_rested" }] }]),
  card("OP09-036", [{ trigger: "on_play", text: "[On Play] If you have 2 or more rested Characters",
    effect: when(exists(myChar({ rested: true }), 2), rest(upTo(1, oppCharOrDon({ cost: le(6) })))) }]),
  card("OP09-044", [{ trigger: "when_attacking", text: "[When Attacking] Look at 5 cards from the top of your deck; reveal up to 1 {Land of Wano}",
    effect: seq(look(5, { any: [{ traits: ["Land of Wano"] }, { traitIncludes: [WB] }] }, 1, true), discard(1)) }]),
  card("OP09-046", [{ trigger: "on_play", text: "[On Play] Play up to 1 {Cross Guild} type Character card",
    effect: play(upTo(1, sel("you", "hand", { ...CHAR, cost: le(5), any: [{ traits: ["Cross Guild"] }, { traitIncludes: ["Baroque Works"] }] }))) }]),
  card("OP09-056", [{ trigger: "on_play", text: "[On Play] Look at 4 cards from the top of your deck; reveal up to 1 {Cross Guild}",
    effect: look(4, { notNames: ["Mr.3(Galdino)"], any: [{ traits: ["Cross Guild"] }, { traitIncludes: ["Baroque Works"] }] }, 1, true) }]),
  card("OP09-059", [{ trigger: "counter", text: "[Counter] Up to 1 of your Leader or Character cards gains +3000 power during this battle. Then, trash up to 2",
    effect: seq(power(upTo(1, myLeaderOrChar()), 3000, "battle"), discard(2, { min: 0 }), { do: "mill", player: "you", count: { count: { of: "var", name: "_discard" } } }) }]),
  card("OP09-061", [{ trigger: "on_event", oncePerTurn: true, text: "[Your Turn] [Once Per Turn] When 2 or more DON!! cards",
    eventTrigger: { event: "don_returned", player: "you", minCount: 2 }, conditions: [{ c: "your_turn" }], effect: seq(addDon(1, false), addDon(1, true)) }]),
  card("OP09-065", [{ trigger: "on_play", text: "[On Play] You may return 1 or more DON!!", costs: [{ k: "return_don_any" }],
    effect: seq(keyword(self, "rush"), rest(upTo(1, oppChar({ cost: le(6) })))) }]),
  card("OP09-068", [{ trigger: "end_of_your_turn", text: "[End of Your Turn] You may return 1 or more DON!!", costs: [{ k: "return_don_any" }],
    effect: seq({ do: "activate", target: self }, keyword(self, "blocker", "until_end_of_opponent_next_turn")) }]),
  card("OP09-070", [{ trigger: "on_play", text: "[On Play] You may return 1 or more DON!!", costs: [{ k: "return_don_any" }],
    effect: { do: "give_don", target: exactly(1, myLeaderOrChar()), count: 2, donState: "rested" } }]),
  card("OP09-073", [{ trigger: "when_attacking", text: "[When Attacking] You may return 1 or more DON!!", costs: [{ k: "return_don_any" }],
    effect: power(upTo(2, oppChar()), -2000) }]),
  card("OP09-076", [{ trigger: "on_play", text: "[On Play] You may return 1 or more DON!!", costs: [{ k: "return_don_any" }], effect: addDon(1, false) }]),
  card("OP09-081", [
    { trigger: "static", text: "Your [On Play] effects are negated.", statics: [{ s: "player_restrict", player: "you", restriction: "on_play_negated" }] },
    { trigger: "activate_main", text: "[Activate: Main] You may trash 1 card from your hand: Your opponent's [On Play] effects are negated",
      costs: [{ k: "trash_hand", count: 1 }], effect: { do: "player_restrict", player: "opponent", restriction: "on_play_negated", duration: "until_end_of_opponent_next_turn" } },
  ]),
  card("OP09-084", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] If your Leader has the {Blackbeard Pirates} type",
    effect: when(leaderTrait("Blackbeard Pirates"), oneOf(
      ["[Double Attack]", keyword(self, "double_attack", "until_end_of_opponent_next_turn")],
      ["[Banish]", keyword(self, "banish", "until_end_of_opponent_next_turn")],
      ["[Blocker]", keyword(self, "blocker", "until_end_of_opponent_next_turn")],
    )) }]),
  card("OP09-101", [{ trigger: "on_play", text: "[On Play] Place 1 of your opponent's Characters with a cost of 3 or less",
    effect: seq(select("_c", oppChar({ cost: le(3) }), 0, 1),
      when({ c: "var_count", name: "_c", op: ">=", value: 1 }, seq({ do: "to_life", target: v("_c"), position: "top_or_bottom", faceUp: true }, { do: "discard", player: "opponent", count: 1 }))) }]),
  card("OP09-119", [{ trigger: "on_play", text: "[On Play] You may return 1 or more DON!!", costs: [{ k: "return_don_any" }], effect: seq(draw(1), keyword(self, "rush")) }]),
  card("OP10-022", [{ trigger: "activate_main", don: 1, oncePerTurn: true, text: "[DON!! x1] [Activate: Main] [Once Per Turn] If the total cost of your Characters",
    conditions: [cmp({ count: { of: "total", selector: myChar(), field: "cost" } }, ">=", 5)],
    costs: [{ k: "return_cards_to_hand", selector: myChar(), count: 1 }],
    effect: seq({ do: "reveal_top", player: "you", bind: "_r", zone: "life" },
      when({ c: "var_all_match", name: "_r", filter: { ...CHAR, traits: ["Supernovas"], cost: le(5) } }, may(play(v("_r"))))) }]),
  card("OP10-026", [{ trigger: "activate_main", text: "[Activate: Main] You may place this Character and 1 [Kin'emon] with 0 power",
    costs: [{ k: "trash_to_deck_bottom", count: 1, filter: { names: ["Kin'emon"], power: eq(0) } }, { k: "self_to_deck_bottom" }],
    effect: play(upTo(1, sel("you", "hand", { names: ["Kin'emon"], cost: eq(6) }))) }]),
  card("OP10-027", [{ trigger: "activate_main", text: "[Activate: Main] You may place this Character and 1 [Kin'emon] with 1000 power",
    costs: [{ k: "trash_to_deck_bottom", count: 1, filter: { names: ["Kin'emon"], power: eq(1000) } }, { k: "self_to_deck_bottom" }],
    effect: play(upTo(1, sel("you", "hand", { names: ["Kin'emon"], cost: eq(6) }))) }]),
  card("OP10-032", [{ trigger: "replacement", text: "If you have a green Character other than [Tashigi]",
    replacement: { event: "removed_by_opponent_effect", target: myChar({ colors: ["green"], notNames: ["Tashigi"] }), byOpponent: true, instead: { do: "pay", costs: [{ k: "rest_self" }], then: { do: "nothing" } }, optional: true } }]),
  card("OP10-036", [{ trigger: "on_event", oncePerTurn: true, text: "[Your Turn] [Once Per Turn] If a Character is rested by your effect",
    eventTrigger: { event: "character_rested", player: "any", byYourEffect: true }, conditions: [{ c: "your_turn" }], effect: { do: "set_don_active", count: 1 } }]),
  card("OP10-057", [{ trigger: "on_play", text: "[On Play] You may rest your Leader or 1 of your Stage cards",
    costs: [{ k: "rest_cards", selector: sel("you", "leader", undefined, [sel("you", "stage")]), count: 1 }],
    effect: when(leaderName("Usopp"), seq(look(5, { traits: ["Dressrosa"], notNames: ["Leo"] }, 2, true), discard(1))) }]),
  card("OP10-058", [{ trigger: "on_play", text: "[On Play] If there is a Character with a cost of 8 or more, draw 1 card. Then, reveal up to 2",
    effect: seq(
      when(exists(sel("any", "character", { cost: ge(8) })), draw(1)),
      select("_a", sel("you", "hand", { ...CHAR, traits: ["Dressrosa"], cost: le(7), notNames: ["Rebecca"] }), 0, 1),
      select("_b", sel("you", "hand", { ...CHAR, traits: ["Dressrosa"], cost: le(4), notNames: ["Rebecca"], excludeVar: "_a" }), 0, 1),
      { do: "reveal", target: v("_a") }, { do: "reveal", target: v("_b") },
      play(v("_a")), play(v("_b"), true),
    ) }]),
  card("OP10-098", [{ trigger: "trigger", text: "[Trigger] Negate the effect of up to 1 of each of your opponent's Leader and Character",
    effect: seq({ do: "negate", target: upTo(1, sel("opponent", "leader")), duration: "turn" }, { do: "negate", target: upTo(1, oppChar()), duration: "turn" }) }]),
  card("OP10-118", [{ trigger: "replacement", oncePerTurn: true, text: "Once per turn, this Character cannot be KO'd by your opponent's effects.",
    replacement: { event: "ko_by_effect", target: "self", byOpponent: true, instead: { do: "nothing" }, optional: false } }]),
  card("OP10-119", [{ trigger: "on_play", text: "[On Play] Reveal up to 1 {Supernovas} type Character card from your hand",
    effect: seq({ do: "hand_to_life", count: 1, min: 0, position: "top", faceUp: false, filter: { ...CHAR, traits: ["Supernovas"] } },
      when(leaderTrait("Supernovas"), { do: "give_don", target: myLeader, count: 1, donState: "rested" })) }]),
  card("OP11-005", [{ trigger: "static", don: 1, text: "[DON!! x1] This Character cannot be KO'd by effects of Characters without",
    statics: [{ s: "restrict", target: "self", restriction: "cannot_be_ko_by_effect_from", filter: { ...CHAR, notAttributes: ["Special"] } }] }]),
  card("OP11-023", [{ trigger: "static", text: "If your Leader has the {Fish-Man} type, you have 3 or less Life cards",
    conditions: [leaderTrait("Fish-Man"), cmp(lifeCount, "<=", 3), cmp({ count: { of: "sum", exprs: [{ of: "don_rested", player: "opponent" }, { of: "cards", selector: sel("opponent", "field", { rested: true }) }] } }, ">=", 5)],
    statics: [{ s: "play_cost", target: "self", amount: -3 }] }]),
  card("OP11-043", [{ trigger: "on_opp_attack", oncePerTurn: true, text: "[On Your Opponent's Attack] [Once Per Turn] This effect can be activated when you only have",
    conditions: [none(myChar({ notTraitIncludes: ["GERMA"] }))],
    effect: may(seq(power(upTo(1, myLeaderOrChar()), 1000, "battle"), { do: "mill", player: "you", count: 2 })) }]),
  card("OP11-046", [{ trigger: "static", text: "If you only have Characters with a type including \"GERMA\"",
    conditions: [none(myChar({ notTraitIncludes: ["GERMA"] }))],
    statics: [{ s: "restrict", target: "self", restriction: "cannot_be_ko_by_opponent_effect" }, { s: "restrict", target: "self", restriction: "cannot_be_rested_by_opponent_effect" }] }]),
  card("OP11-050", [{ trigger: "when_attacking", text: "[When Attacking] You may trash 1 {Firetank Pirates}",
    costs: [{ k: "trash_hand", count: 1, filter: { traits: ["Firetank Pirates"] } }],
    effect: seq(select("_t", sel("any", "character", { cost: le(1) }), 0, 1),
      oneOf(["Return it to the owner's hand", { do: "to_hand", target: v("_t") }], ["Place it at the bottom of the owner's deck", { do: "to_deck", target: v("_t"), position: "bottom" }])) }]),
  card("OP11-066", [{ trigger: "activate_main", text: "[Activate: Main] You may rest this Character: Choose a cost", costs: [{ k: "rest_self" }],
    effect: seq(guessCost(ko(upTo(1, oppChar({ baseCost: le(3) })))), addDon(1, true)) }]),
  card("OP11-071", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand: Choose a cost",
    costs: [{ k: "trash_hand", count: 1 }], effect: guessCost(seq(draw(1), addDon(1, false))) }]),
  card("OP11-073", [{ trigger: "on_opp_attack", oncePerTurn: true, text: "[On Your Opponent's Attack] [Once Per Turn] DON!! -5: Choose a cost",
    costs: [{ k: "return_don", count: 5 }], effect: guessCost(power(upTo(1, sel("you", "leader")), 2000)) }]),
  card("OP11-074", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] DON!! -1, You may rest this Character: Choose a cost",
    costs: [{ k: "return_don", count: 1 }, { k: "rest_self" }], effect: guessCost(rest(upTo(1, oppChar({ cost: le(4) })))) }]),
  card("OP11-079", [{ trigger: "counter", text: "[Counter] Choose a cost", effect: guessCost(power(upTo(1, myLeaderOrChar()), 5000, "battle")) }]),
  card("OP11-081", [{ trigger: "main", text: "[Main] Choose a cost", effect: guessCost(ko(upTo(1, oppChar({ baseCost: le(8) })))) }]),
  card("OP11-092", [{ trigger: "on_play", text: "[On Play] You may trash 1 card from your hand: Draw 1 card and play up to 1 {SWORD}",
    costs: [{ k: "trash_hand", count: 1 }],
    effect: seq(draw(1), play(upTo(1, sel("you", "trash", { ...CHAR, traits: ["SWORD"], cost: le(8), notNames: ["Helmeppo"] }), { bind: "_p" })),
      { do: "delay", when: "end_of_turn", effect: when(exists(myChar({ inVar: "_p" })), { do: "to_deck", target: v("_p"), position: "bottom" }) }) }]),
  card("OP11-101", [{ trigger: "replacement", oncePerTurn: true, text: "[Once Per Turn] If your {Supernovas} type Character other than",
    replacement: { event: "removed_by_opponent_effect", target: myChar({ traits: ["Supernovas"], notNames: ["Capone\"Gang\"Bege"] }), byOpponent: true, instead: { do: "to_life", target: v("_target"), position: "top", faceUp: false }, optional: true } }]),
  card("OP11-102", [{ trigger: "on_event", oncePerTurn: true, text: "[Your Turn] [Once Per Turn] This effect can be activated when your opponent activates an Event or [Trigger]",
    eventTrigger: { event: "event_activated", player: "opponent", alsoEvents: ["trigger_activated"] }, conditions: [{ c: "your_turn" }],
    effect: when(cmp({ count: { of: "life", player: "opponent" } }, ">=", 2), may(seq({ do: "trash_life", player: "you", count: 1 }, { do: "trash_life", player: "opponent", count: 1 }))) }]),
  card("OP11-110", [{ trigger: "replacement", text: "If this Character would be KO'd, you may rest 1 of your [Fish-Man Island]",
    replacement: { event: "ko", target: "self", instead: { do: "pay", costs: [{ k: "rest_cards", selector: sel("you", "stage", { names: ["Fish-Man Island"] }, [sel("you", "leader", { names: ["Shirahoshi"] })]), count: 1 }], then: { do: "nothing" } }, optional: true } }]),
  card("OP12-001", [{ trigger: "static", text: "Under the rules of this game, you cannot include cards with a cost of 5 or more", statics: [{ s: "deck_rule", rule: "max_cost:4" }] }]),
  card("OP12-006", [{ trigger: "on_play", text: "[On Play] Look at 5 cards from the top of your deck; reveal up to 1 [Monkey.D.Luffy] or 1 red Event",
    effect: look(5, { any: [{ names: ["Monkey.D.Luffy"] }, { types: ["event"], colors: ["red"] }] }, 1, true) }]),
  card("OP12-016", [{ trigger: "main", text: "[Main] You may give 2 active DON!! cards to 1 of your [Silvers Rayleigh]",
    costs: [{ k: "give_don", count: 2, selector: myChar({ names: ["Silvers Rayleigh"] }) }],
    effect: restrict(v("_cost"), "cannot_activate_blocker") }]),
  card("OP12-020", [{ trigger: "activate_main", don: 3, oncePerTurn: true, text: "[DON!! x3] [Activate: Main] [Once Per Turn] If this Leader battles",
    conditions: [{ c: "self_flag", flag: "battled_character" }],
    effect: seq({ do: "activate", target: self }, restrict(self, "cannot_attack_matching", "turn", { filter: { ...CHAR, baseCost: le(7) } })) }]),
  card("OP12-028", [{ trigger: "activate_main", text: "[Activate: Main] You may rest 1 of your DON!! cards and this Character",
    costs: [{ k: "rest_don", count: 1 }, { k: "rest_self" }],
    effect: when(leaderName("Roronoa Zoro"), look(5, { any: [{ attributes: ["Slash"] }, { types: ["event"], colors: ["green"] }] }, 1, true)) }]),
  card("OP12-034", [{ trigger: "on_play", text: "[On Play] If your Leader has the <Slash> attribute, look at 5",
    effect: when(exists(sel("you", "leader", { attributes: ["Slash"] })), look(5, { any: [{ attributes: ["Slash"] }, { types: ["event"], colors: ["green"] }] }, 1, true)) }]),
  card("OP12-036", [
    { trigger: "static", text: "This card in your hand cannot be played by effects.", statics: [{ s: "deck_rule", rule: "not_playable_by_effect" }] },
    { trigger: "static", text: "This card in your hand cannot be played by effects.", conditions: [exists(sel("you", "leader", { attributes: ["Slash"] }))],
      statics: [{ s: "restrict", target: "self", restriction: "cannot_be_ko_in_battle_by_attribute", attribute: "Slash" }, { s: "power", target: "self", amount: 1000 }] },
  ]),
  card("OP12-037", [{ trigger: "main", text: "[Main] You may rest 3 of your DON!! cards: Rest up to a total of 2",
    costs: [{ k: "rest_don", count: 3 }], effect: rest(upTo(2, oppCharOrDon())) }]),
  card("OP12-040", [{ trigger: "on_event", text: "When a card is trashed from your hand by your {Navy} type card's effect",
    eventTrigger: { event: "card_trashed_from_hand", player: "you", sourceFilter: { traits: ["Navy"] } }, effect: draw(1) }]),
  card("OP12-063", [{ trigger: "static", text: "If you have 4 or more Events in your trash",
    conditions: [exists(sel("you", "trash", { types: ["event"] }), 4)], statics: [{ s: "power", target: "self", amount: 2000 }, { s: "cost", target: "self", amount: 5 }] }]),
  card("OP12-070", [
    { trigger: "static", text: "This Character gains +1000 power for every 5 Events", statics: [{ s: "power", target: "self", amount: { count: { of: "cards", selector: sel("you", "trash", { types: ["event"] }) }, per: 5, times: 1000 } }] },
    { trigger: "replacement", text: "This Character gains +1000 power for every 5 Events",
      replacement: { event: "removed_by_opponent_effect", target: "self", byOpponent: true, instead: { do: "pay", costs: [{ k: "return_don", count: 1 }], then: { do: "nothing" } }, optional: true } },
  ]),
  card("OP12-073", [{ trigger: "on_play", text: "[On Play] If the number of DON!! cards on your field is equal to or less",
    effect: seq(when(cmp(donField("you"), "<=", donField("opponent")), addDon(1, false)),
      power({ ref: "all", selector: myChar({ any: [{ names: ["Donquixote Rosinante"] }, { traits: ["Heart Pirates"] }] }) }, 1000, "until_end_of_opponent_next_turn")) }]),
  card("OP12-080", [{ trigger: "activate_main", text: "[Activate: Main] You may place this Stage at the bottom of the owner's deck: If your Leader is [Sanji]",
    costs: [{ k: "self_to_deck_bottom" }], effect: when(leaderName("Sanji"), look(3, { types: ["event"] }, 1, true)) }]),
  card("OP12-081", [
    { trigger: "on_event", text: "When this Leader attacks your opponent's Leader",
      eventTrigger: { event: "attack_declared", player: "you", filter: { types: ["leader"] } },
      conditions: [{ c: "attacker_is_self" }, { c: "battle_against", target: "leader" }, exists(myChar({ cost: ge(8) }), 2)], effect: draw(1) },
    { trigger: "on_event", oncePerTurn: true, text: "[Once Per Turn] This effect can be activated when your opponent plays a Character",
      eventTrigger: { event: "character_played", player: "opponent", filter: { baseCost: ge(8) }, sourceFilter: CHAR, either: true },
      effect: may({ do: "life_to_hand", player: "opponent", count: 1, position: "top" }) },
  ]),
  card("OP12-096", [{ trigger: "main", text: "[Main] KO up to 1 of your opponent's Characters with a cost of 4 or less. If you have",
    effect: when(exists(myChar({ cost: ge(8) })), ko(upTo(1, oppChar({ cost: le(6) }))), ko(upTo(1, oppChar({ cost: le(4) })))) }]),
  card("OP12-099", [{ trigger: "on_event", text: "[Your Turn] When a card is removed from your or your opponent's Life cards",
    eventTrigger: { event: "life_removed", player: "any" }, conditions: [{ c: "your_turn" }],
    effect: seq(draw(1), { do: "player_restrict", player: "you", restriction: "cannot_draw_by_effect", duration: "turn" }) }]),
  card("OP12-102", [{ trigger: "static", text: "[Opponent's Turn] If you have no other [Shirahoshi]",
    conditions: [{ c: "opponent_turn" }, none(myChar({ names: ["Shirahoshi"], baseCost: eq(2), excludeSelf: true }))],
    statics: [{ s: "power", target: { all: myChar({ traits: ["Neptunian"] }) }, amount: 2000 }] }]),
  card("OP12-117", [{ trigger: "main", text: "[Main] You may rest 5 of your DON!! cards: If your Leader has the {Supernovas} type",
    costs: [{ k: "rest_don", count: 5 }],
    effect: when(leaderTrait("Supernovas"), { do: "to_life", target: upTo(1, sel("any", "character", { cost: le(9) })), position: "top_or_bottom", faceUp: false }) }]),
  card("OP13-001", [{ trigger: "on_opp_attack", don: 1, text: "[DON!! x1] [On Your Opponent's Attack] If you have 5 or less active DON!!",
    conditions: [cmp({ count: { of: "don_active", player: "you" } }, "<=", 5)],
    effect: seq(
      select("_d", sel("you", "don", { rested: false }), 0, 10),
      rest(v("_d")),
      power(upTo(1, sel("you", "leader", { onlySelf: true }, [myChar({ traits: ["Straw Hat Crew"] })])), { count: { of: "var", name: "_d" }, times: 2000 }, "battle"),
    ) }]),
  card("OP13-002", [{ trigger: "on_event", don: 1, oncePerTurn: true, text: "[DON!! x1] [Once Per Turn] When you take damage",
    eventTrigger: { event: "leader_damaged", player: "you", alsoEvents: ["character_ko"], filter: { basePower: ge(6000) } }, effect: draw(1) }]),
  card("OP13-003", [{ trigger: "static", text: "If you have any DON!! cards on your field, 1 DON!! card placed",
    statics: [{ s: "deck_rule", rule: "don_phase_give_leader" }, { s: "power", target: "self", amount: -2000, when: [cmp(donField("you"), "<=", 9)] }] }]),
  card("OP13-004", [{ trigger: "static", don: 1, text: "[DON!! x1] If you have a Character with a cost of 8 or more",
    conditions: [exists(myChar({ cost: ge(8) }))], statics: [{ s: "power", target: { all: myLeaderOrChar() }, amount: 1000 }] }]),
  card("OP13-007", [{ trigger: "activate_main", text: "[Activate: Main] You may give 1 of your active DON!! cards",
    costs: [{ k: "give_don", count: 1, selector: myLeaderOrChar({ excludeSelf: true }) }, { k: "trash_self" }], effect: power(upTo(1, oppChar()), -3000) }]),
  card("OP13-044", [{ trigger: "when_attacking", text: "[When Attacking] Give up to 1 rested DON!! card to your Leader with a type including",
    effect: { do: "give_don", target: exactly(1, myLeaderOrChar({ traitIncludes: [WB] })), count: 1, donState: "rested" } }]),
  card("OP13-046", [{ trigger: "replacement", oncePerTurn: true, text: "[Once Per Turn] If this Character would be KO'd or would be removed",
    replacement: { event: "ko", alsoEvents: ["removed_by_opponent_effect"], target: "self", instead: { do: "pay", costs: [{ k: "trash_hand", count: 1, filter: { traitIncludes: [WB] } }], then: { do: "nothing" } }, optional: true } }]),
  card("OP13-057", [{ trigger: "main", text: "[Main] You may rest 1 of your DON!! cards: If you have 1 or less Life cards",
    costs: [{ k: "rest_don", count: 1 }], effect: when(cmp(lifeCount, "<=", 1), restrict(myLeader, "cannot_activate_blocker")) }]),
  card("OP13-064", [{ trigger: "static", text: "Your Leader and all of your Characters that do not have a type including \"Roger Pirates\"",
    statics: [{ s: "negate", target: { all: myLeaderOrChar({ notTraitIncludes: ["Roger Pirates"] }) } }] }]),
  card("OP13-066", [{ trigger: "on_play", text: "[On Play] If you have any DON!! cards given",
    effect: seq(when(cmp({ count: { of: "don_attached_total", player: "you" } }, ">=", 1), rest(upTo(1, oppChar({ cost: le(5) })))),
      { do: "delay", when: "end_of_turn", effect: addDon(1, false) }) }]),
  card("OP13-079", [
    { trigger: "static", text: "Under the rules of this game, you cannot include Events with a cost of 2 or more",
      statics: [{ s: "deck_rule", rule: "no_events_cost_ge:2" }, { s: "deck_rule", rule: "start_stage:Mary Geoise" }] },
    { trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may trash 1 of your {Celestial Dragons}",
      costs: [{ k: "either", labels: ["Trash 1 of your {Celestial Dragons} type Characters", "Trash 1 card from your hand"], options: [[{ k: "trash_cards", selector: myChar({ traits: ["Celestial Dragons"] }), count: 1 }], [{ k: "trash_hand", count: 1 }]] }],
      effect: draw(1) },
  ]),
  card("OP13-082", [{ trigger: "activate_main", text: "[Activate: Main] If your Leader is [Imu], you may rest 1 of your DON!!",
    conditions: [leaderName("Imu")], costs: [{ k: "rest_don", count: 1 }, { k: "trash_hand", count: 1 }],
    effect: seq({ do: "to_trash", target: { ref: "all", selector: myChar() } },
      play(upTo(5, sel("you", "trash", { ...CHAR, traits: ["Five Elders"], power: eq(5000) }), { distinctNames: true }))) }]),
  card("OP13-084", [{ trigger: "static", text: "[Your Turn] If you have 10 or more cards in your trash",
    conditions: [{ c: "your_turn" }, cmp(trashCount, ">=", 10)], statics: [{ s: "base_power", target: { all: myChar({ traits: ["Five Elders"] }) }, value: 7000 }] }]),
  card("OP14-001", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] Select 2 of your {Supernovas} or {Heart Pirates}",
    effect: { do: "swap_base_power", target: exactly(2, myChar({ traits: ["Supernovas", "Heart Pirates"] })), duration: "turn" } }]),
  card("OP14-003", [{ trigger: "static", text: "This Character cannot be KO'd by effects of your opponent's Characters with 5000 base power",
    statics: [{ s: "restrict", target: "self", restriction: "cannot_be_ko_by_opponent_effect_from", filter: { ...CHAR, basePower: le(5000) } }] }]),
  card("OP14-009", [{ trigger: "on_opp_attack", oncePerTurn: true, text: "[On Your Opponent's Attack] [Once Per Turn] You may trash 2 cards from your hand: Select your Leader",
    costs: [{ k: "trash_hand", count: 2 }], effect: { do: "swap_base_power", target: myLeader, with: exactly(1, myChar()), duration: "battle" } }]),
  card("OP14-017", [{ trigger: "main", text: "[Main] Select 2 of your opponent's Characters with 9000 base power",
    effect: { do: "swap_base_power", target: exactly(2, oppChar({ basePower: le(9000) })), duration: "turn" } }]),
  card("OP14-053", [{ trigger: "static", text: "[Opponent's Turn] If you have 7 or less cards in your hand",
    conditions: [{ c: "opponent_turn" }, cmp({ count: { of: "hand", player: "you" } }, "<=", 7)],
    statics: [{ s: "base_power", target: "self", value: { count: { of: "leader_base_power", player: "you" } } }] }]),
  card("OP14-056", [
    { trigger: "static", text: "This Character cannot attack. When a card is trashed", statics: [{ s: "restrict", target: "self", restriction: "cannot_attack" }] },
    { trigger: "on_event", text: "This Character cannot attack. When a card is trashed", eventTrigger: { event: "card_trashed_from_hand", player: "you", byEffect: true },
      effect: { do: "negate", target: self, duration: "turn" } },
  ]),
  card("OP14-060", [{ trigger: "on_opp_attack", oncePerTurn: true, text: "[On Your Opponent's Attack] [Once Per Turn] DON!! -1: Select your Leader",
    costs: [{ k: "return_don", count: 1 }], effect: { do: "redirect_attack", target: exactly(1, sel("you", "leader", undefined, [myChar({ traits: ["Donquixote Pirates"] })])) } }]),
  card("OP14-067", [{ trigger: "on_ko", text: "[On KO] Add up to 1 DON!! card from your DON!! deck and rest it, look at 5",
    effect: seq(addDon(1, true), look(5, { traits: ["Donquixote Pirates"] }, 1, true)) }]),
  card("OP14-070", [{ trigger: "on_event", text: "When this Character becomes rested by your opponent's Character's effect",
    eventTrigger: { event: "self_rested", player: "you", byOpponentEffect: true, sourceFilter: CHAR },
    effect: may({ do: "activate", target: self }, [{ k: "return_don", count: 1 }]) }]),
  card("OP14-079", [{ trigger: "static", text: "All of your opponent's Characters cannot be removed from the field by your effects.",
    statics: [{ s: "restrict", target: { all: oppChar() }, restriction: "cannot_be_removed_by_opponent_effect" }] }]),
  card("OP14-084", [{ trigger: "on_play", text: "[On Play] If your Leader's type includes \"Baroque Works\", play up to 1",
    effect: when(leaderTraitIncludes("Baroque Works"), seq(
      play(upTo(1, sel("you", "trash", { ...CHAR, traitIncludes: ["Baroque Works"], cost: le(4) }))),
      play(upTo(1, sel("you", "trash", { ...CHAR, traitIncludes: ["Baroque Works"], cost: eq(1) }))),
    )) }]),
  card("OP14-104", [{ trigger: "on_play", text: "[On Play] Select up to 1 {Thriller Bark Pirates} type Character",
    effect: seq(select("_s", sel("you", "trash", { ...CHAR, traits: ["Thriller Bark Pirates"], cost: le(4) }), 0, 1),
      oneOf(["Play it", play(v("_s"))], ["Add it to the top of your Life cards face-up", { do: "to_life", target: v("_s"), position: "top", faceUp: true }])) }]),
  card("OP15-002", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] If you have activated an Event",
    conditions: [{ c: "this_turn", what: "event_activated", player: "you", filter: { baseCost: ge(3) } }], effect: draw(1) }]),
  card("OP15-003", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may give 1 of your opponent's rested DON!!",
    costs: [{ k: "give_opponent_don", count: 1 }], effect: giveDonChoice("rested") }]),
  card("OP15-008", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] If this Character was played on this turn",
    conditions: [{ c: "self_played_this_turn" }], effect: power({ ref: "all", selector: oppChar() }, { count: { of: "don_attached_self" }, times: -1000 }) }]),
  card("OP15-010", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] Give up to 1 rested DON!!", effect: giveDonChoice("rested") }]),
  card("OP15-012", [{ trigger: "when_attacking", text: "[When Attacking] Give up to 1 rested DON!!", effect: giveDonChoice("rested") }]),
  card("OP15-017", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may give 1 of your opponent's rested DON!!",
    costs: [{ k: "give_opponent_don", count: 1 }], effect: giveDonChoice("rested") }]),
  card("OP15-022", [{ trigger: "static", text: "Under the rules of this game, you do not lose when your deck has 0 cards.", statics: [{ s: "deck_rule", rule: "deck_out_end_of_turn" }] }]),
  card("OP15-023", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may give 1 of your opponent's rested DON!!",
    costs: [{ k: "give_opponent_don", count: 1 }], effect: giveDonChoice("any") }]),
  card("OP15-024", [{ trigger: "static", text: "[Opponent's Turn] This Character cannot be rested by your opponent's Leader and Character effects",
    conditions: [{ c: "opponent_turn" }],
    statics: [{ s: "restrict", target: "self", restriction: "cannot_be_rested_by_opponent_effect_from", filter: { types: ["leader", "character"] } }, { s: "keyword", target: "self", keyword: "blocker" }] }]),
  card("OP15-025", [{ trigger: "on_play", text: "[On Play] Give up to 2 DON!! cards from your opponent's cost area",
    effect: seq({ do: "give_don", target: exactly(1, oppChar()), count: 2, donState: "any", player: "opponent" },
      { do: "delay", when: "end_of_turn", effect: restrict(upTo(1, oppChar({ rested: true, donGiven: ge(3) })), "no_refresh", "permanent") }) }]),
  card("OP15-028", [{ trigger: "on_play", text: "[On Play] If your Leader has the {East Blue} type, give up to 1 DON!!",
    effect: when(leaderTrait("East Blue"), { do: "give_don", target: exactly(1, oppChar()), count: 1, donState: "any", player: "opponent" }) }]),
  card("OP15-031", [{ trigger: "on_play", text: "[On Play] Select up to 1 of your opponent's rested Characters. If the chosen",
    effect: seq(select("_s", oppChar({ rested: true }), 0, 1), when({ c: "var_all_match", name: "_s", filter: { costEqDonGiven: true } }, ko(v("_s")))) }]),
  card("OP15-073", [{ trigger: "on_play", text: "[On Play] Play up to 1 [Heavenly Warriors] with a cost of 1",
    effect: play(upTo(1, sel("you", "hand", { cost: eq(1), any: [{ names: ["Heavenly Warriors"] }, { ...CHAR, traits: ["Vassals"] }] }))) }]),
  card("OP15-080", [{ trigger: "static", text: "If you have [Gecko Moria] with 10000 power or more on your field",
    conditions: [exists(myLeaderOrChar({ names: ["Gecko Moria"], power: ge(10000) })), none(sel("you", "field", { names: ["Oars"], excludeSelf: true }))],
    statics: [{ s: "power", target: "self", amount: 7000 }] }]),
  card("OP15-092", [{ trigger: "static", text: "Apply each of the following effects based on the number of cards in your trash",
    statics: [
      { s: "base_power", target: "self", value: 9000, when: [cmp(trashCount, ">=", 10)] },
      { s: "cost", target: "self", amount: 10, when: [cmp(trashCount, ">=", 10)] },
      { s: "base_power", target: { all: sel("you", "leader") }, value: 7000, when: [cmp(trashCount, ">=", 20), { c: "opponent_turn" }] },
      { s: "power", target: "self", amount: 1000, when: [cmp(trashCount, ">=", 30)] },
    ] }]),
  card("OP15-093", [{ trigger: "activate_main", text: "[Activate: Main] You may trash this Character: If you have 15 or more cards",
    costs: [{ k: "trash_self" }],
    effect: when(cmp(trashCount, ">=", 15), seq(select("_l", myChar({ names: ["Monkey.D.Luffy"] }), 0, 1), keyword(v("_l"), "rush_character"), { do: "attribute", target: v("_l"), attribute: "Slash", duration: "turn" })) }]),
  card("OP15-098", [{ trigger: "replacement", text: "If your {Sky Island} type Character with 6000 base power",
    replacement: { event: "removed_by_opponent_effect", alsoEvents: ["ko_in_battle"], target: myChar({ traits: ["Sky Island"], basePower: ge(6000) }), byOpponent: true,
      instead: { do: "pay", costs: [{ k: "life_to_hand", count: 1, position: "top" }], then: { do: "nothing" } }, optional: true } }]),
  card("OP15-118", [{ trigger: "on_play", text: "[On Play] DON!! -1: Look at 5 cards", costs: [{ k: "return_don", count: 1 }], effect: seq(look(5, null, 1, false), discard(1)) }]),
  card("OP15-119", [
    { trigger: "static", text: "If you have 6 or more DON!! cards on your field, this Character gains [Rush].", conditions: [cmp(donField("you"), ">=", 6)], statics: [{ s: "keyword", target: "self", keyword: "rush" }] },
    { trigger: "on_event", text: "If you have 6 or more DON!! cards on your field, this Character gains [Rush].",
      eventTrigger: { event: "event_activated", player: "opponent", alsoEvents: ["blocker_activated"] },
      effect: seq({ do: "reveal_top", player: "you", bind: "_r", zone: "life" }, power(self, { count: { of: "var_sum", name: "_r", field: "cost" }, times: 1000 })) },
  ]),
  card("OP16-001", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] Up to 1 of your [Monkey.D.Luffy] Characters",
    effect: keyword(upTo(1, myChar({ power: ge(8000), any: [{ names: ["Monkey.D.Luffy"] }, { traitIncludes: [WB] }] })), "rush") }]),
  card("OP16-015", [{ trigger: "static", text: "If your Leader's card name includes \"Ace\"",
    conditions: [exists(sel("you", "leader", { nameIncludes: ["Ace"] })), cmp(donField("you"), ">=", 6)], statics: [{ s: "play_cost", target: "self", amount: -2 }] }]),
  card("OP16-038", [{ trigger: "main", text: "[Main] You may rest 6 of your DON!! cards: If you have 5 {Impel Down}",
    costs: [{ k: "rest_don", count: 6 }],
    effect: when(cmp({ count: { of: "distinct_names", selector: myChar({ traits: ["Impel Down"] }) } }, ">=", 5),
      seq({ do: "activate", target: myLeader }, { do: "activate", target: { ref: "all", selector: myChar() } })) }]),
  card("OP16-041", [{ trigger: "on_event", don: 1, oncePerTurn: true, text: "[DON!! x1] [Once Per Turn] This effect can be activated when your {Impel Down}",
    eventTrigger: { event: "character_left_field", player: "you", filter: { traits: ["Impel Down"] } },
    effect: may(play(upTo(1, sel("you", "hand", { names: ["Prisoner of Impel Down"] })))) }]),
  card("OP16-079", [{ trigger: "on_event", text: "When a {Land of Wano} type Character card is played from your trash",
    eventTrigger: { event: "character_played", player: "you", fromZone: "trash", filter: { ...CHAR, traits: ["Land of Wano"] } }, effect: keyword({ ref: "event_card" }, "rush") }]),
  card("OP16-084", [{ trigger: "activate_main", text: "[Activate: Main] You may trash this Character with a cost of 20 or more",
    conditions: [exists(myChar({ onlySelf: true, cost: ge(20) }))], costs: [{ k: "trash_self" }],
    effect: when(cmp(donField("you"), ">=", 9), play(upTo(1, sel("you", "trash", { names: ["Kouzuki Momonosuke"], cost: eq(9) })))) }]),
  card("OP16-100", [{ trigger: "main", text: "[Main] You may rest 2 of your DON!! cards: If your opponent's Character has been KO'd",
    costs: [{ k: "rest_don", count: 2 }],
    effect: when({ c: "and", conds: [{ c: "this_turn", what: "character_koed", player: "opponent" }, leaderName("Yamato")] }, { do: "activate", target: myLeader }) }]),
  card("OP16-105", [{ trigger: "trigger", text: "[Trigger] If you have 1 or less Life cards, play up to 1 [Absalom]",
    effect: when(cmp(lifeCount, "<=", 1), seq(...["Absalom", "Dr. Hogback", "Perona"].map((name) => play(upTo(1, sel("you", "trash", { ...CHAR, names: [name], cost: le(4) })))))) }]),
  card("OP17-004", [{ trigger: "on_play", text: "[On Play] Up to 1 of your {Land of Wano} type Characters or up to 1",
    effect: keyword(upTo(1, myChar({ any: [{ traits: ["Land of Wano"] }, { traitIncludes: [WB] }] })), "rush") }]),
  card("OP17-007", [{ trigger: "on_play", text: "[On Play] If your Leader is [Edward.Newgate] or has the {Land of Wano} type",
    effect: when({ c: "or", conds: [leaderName("Edward.Newgate"), leaderTrait("Land of Wano")] },
      play(upTo(1, sel("you", "hand", { ...CHAR, power: le(6000), any: [{ traits: ["Land of Wano"] }, { traitIncludes: [WB] }] })))) }]),
  card("OP17-020", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may trash 1 card from your hand or rest 1",
    costs: [{ k: "either", labels: ["Trash 1 card from your hand", "Rest 1 of your DON!! cards"], options: [[{ k: "trash_hand", count: 1 }], [{ k: "rest_don", count: 1 }]] }],
    effect: restrict(upTo(1, oppChar({ rested: true })), "no_refresh", "permanent") }]),
  card("OP17-040", [{ trigger: "on_event", oncePerTurn: true, text: "[Once Per Turn] When your Leader with a type including \"Rocks Pirates\" attacks or is attacked",
    eventTrigger: { event: "attack_declared", player: "you", filter: { types: ["leader"], traitIncludes: ["Rocks Pirates"] }, alsoEvents: ["leader_attacked"] },
    effect: may(power(myLeader, 3000, "battle"), [{ k: "trash_hand", count: 1 }]) }]),
  card("OP17-044", [{ trigger: "static", text: "If your Leader's type includes \"Rocks Pirates\" and this Character is rested",
    conditions: [leaderTraitIncludes("Rocks Pirates"), { c: "self_rested", value: true }],
    statics: [{ s: "player_restrict", player: "opponent", restriction: "attack_only_matching", filter: { ...CHAR, names: ["Captain John"] } }] }]),
  card("OP17-055", [{ trigger: "counter", text: "[Counter] Up to 1 of your Leader with a type including \"Rocks Pirates\"",
    effect: power(upTo(1, myLeaderOrChar({ traitIncludes: ["Rocks Pirates"] })), 2000, "battle") }]),
  card("OP17-095", [
    { trigger: "static", text: "If there is a Character with a cost of 12 or more", conditions: [exists(sel("any", "character", { cost: ge(12) }))], statics: [{ s: "power", target: "self", amount: 3000 }] },
    { trigger: "replacement", text: "If there is a Character with a cost of 12 or more",
      replacement: { event: "removed_by_opponent_effect", target: myChar(), byOpponent: true, instead: { do: "pay", costs: [{ k: "trash_to_deck_bottom", count: 3 }], then: { do: "nothing" } }, optional: true } },
  ]),
  card("OP17-118", [{ trigger: "static", text: "If you only have Characters without a Counter",
    conditions: [none(myChar({ hasCounter: true }))], statics: [{ s: "counter", filter: { onlySelf: true }, mode: "add", value: 2000 }] }]),
  card("P-025", [{ trigger: "static", don: 1, text: "[DON!! x1] This Character cannot be KO'd in battle by Characters without",
    statics: [{ s: "restrict", target: "self", restriction: "cannot_be_ko_in_battle_by", filter: { ...CHAR, notAttributes: ["Special"] } }] }]),
  card("P-059", [{ trigger: "counter", text: "[Counter] If your Leader is [Uta], you may return any number of Characters",
    effect: seq(when(leaderName("Uta"), seq(select("_r", sel("you", "character"), 0, 5), { do: "to_hand", target: v("_r") })),
      power(upTo(1, myLeaderOrChar()), { count: { of: "var", name: "_r" }, times: 2000 }, "battle")) }]),
  card("P-067", [{ trigger: "static", text: "If this Character is rested, your opponent cannot attack any card other than",
    conditions: [{ c: "self_rested", value: true }], statics: [{ s: "player_restrict", player: "opponent", restriction: "attack_only_matching", filter: { ...CHAR, names: ["Eustass\"Captain\"Kid"] } }] }]),
  card("P-077", [{ trigger: "on_event", oncePerTurn: true, text: "[Once Per Turn] When 2 or more DON!! cards",
    eventTrigger: { event: "don_returned", player: "you", minCount: 2 }, effect: seq(addDon(1, true), { do: "activate", target: upTo(1, sel("you", "stage", { colors: ["purple"] })) }) }]),
  card("P-117", [{ trigger: "static", text: "Under the rules of this game, you can only include {East Blue} type cards",
    statics: [{ s: "deck_rule", rule: "only_trait:East Blue" }, { s: "deck_rule", rule: "deck_out_win" }] }]),
  card("P-118", [{ trigger: "on_play", text: "[On Play] If your Leader has the {Egghead} type, play up to 1",
    effect: when(leaderTrait("Egghead"), play(upTo(1, sel("you", "hand", { ...CHAR, cost: le(5), any: [{ traits: ["Egghead"] }, { hasTrigger: true }] })))) }], ["[Trigger], with a cost of 5 or less"]),
  card("P-142", [{ trigger: "replacement", text: "If your {Straw Hat Crew} type Character with 8000 base",
    replacement: { event: "ko", target: myChar({ traits: ["Straw Hat Crew"], basePower: le(8000) }), instead: { do: "pay", costs: [{ k: "trash_self" }], then: { do: "nothing" } }, optional: true } }]),
  card("PRB02-005", [{ trigger: "on_play", text: "[Your Turn] [On Play] If your Leader is multicolored",
    conditions: [{ c: "your_turn" }],
    effect: when({ c: "and", conds: [{ c: "leader_multicolor" }, cmp(donField("opponent"), "<=", 7)] }, { do: "delay", when: "opponent_main", effect: { do: "rest_don", player: "opponent", count: 1 } }) }]),
  card("PRB02-006", [{ trigger: "replacement", text: "[Opponent's Turn] If this Character would be rested by your opponent's Character's effect",
    conditions: [{ c: "opponent_turn" }],
    replacement: { event: "rested_by_opponent_effect", target: "self", byOpponent: true, sourceFilter: CHAR, instead: { do: "pay", costs: [{ k: "rest_cards", selector: myChar({ excludeSelf: true }), count: 1 }], then: { do: "nothing" } }, optional: true } }]),
  card("PRB02-009", [{ trigger: "on_event", text: "This effect can be activated when this Character is rested by your opponent's effect.",
    eventTrigger: { event: "self_rested", player: "you", byOpponentEffect: true }, effect: may(seq({ do: "to_trash", target: self }, draw(2))) }]),
  card("PRB02-017", [{ trigger: "on_play", text: "[On Play] You may trash 1 card with a [Trigger] from your hand",
    costs: [{ k: "trash_hand", count: 1, filter: { hasTrigger: true } }],
    effect: restrict(upTo(1, sel("opponent", "leader", { rested: true }, [oppChar({ notNames: ["Monkey.D.Luffy"] })])), "cannot_attack", "until_end_of_opponent_next_turn") }]),
  card("ST02-010", [{ trigger: "on_event", don: 1, oncePerTurn: true, text: "[DON!! x1] [Once Per Turn] [Your Turn] If this Character battles",
    eventTrigger: { event: "battle_ended_vs_character", player: "you" }, conditions: [{ c: "your_turn" }], effect: { do: "activate", target: self } }]),
  card("ST02-014", [{ trigger: "static", don: 1, text: "[DON!! x1] [Your Turn] If this Character is rested",
    conditions: [{ c: "your_turn" }, { c: "self_rested", value: true }], statics: [{ s: "power", target: { all: myLeaderOrChar({ traits: ["Supernovas", "Navy"] }) }, amount: 1000 }] }]),
  card("ST05-010", [{ trigger: "static", text: "When this Character battles <Strike> attribute Characters",
    conditions: [{ c: "battle_opponent", filter: { ...CHAR, attributes: ["Strike"] } }], statics: [{ s: "power", target: "self", amount: 3000 }] }]),
  card("ST08-013", [{ trigger: "on_event", don: 1, text: "[DON!! x1] At the end of a battle in which this Character battles",
    eventTrigger: { event: "battle_ended_vs_character", player: "you" },
    effect: may(seq(ko({ ref: "battle", role: "opponent_battler" }), when({ c: "var_count", name: "_affected", op: ">=", value: 1 }, ko(self)))) }]),
  card("ST10-002", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] If you have 0 DON!! cards",
    conditions: [{ c: "or", conds: [cmp(donField("you"), "==", 0), cmp(donField("you"), ">=", 8)] }], effect: addDon(1, false) }]),
  card("ST12-003", [{ trigger: "on_play", text: "[On Play] If you have 2 or less Characters, play up to 1 {Muggy Kingdom}",
    effect: when(cmp(count(myChar()), "<=", 2), play(upTo(1, sel("you", "hand", { ...CHAR, cost: le(4), notNames: ["Dracule Mihawk"], any: [{ traits: ["Muggy Kingdom"] }, { attributes: ["Slash"] }] })), true)) }]),
  card("ST13-001", [{ trigger: "activate_main", don: 1, oncePerTurn: true, text: "[DON!! x1] [Activate: Main] [Once Per Turn] You may add 1 of your Characters",
    conditions: [exists(myChar({ cost: ge(3), power: ge(7000) }))],
    effect: seq({ do: "to_life", target: exactly(1, myChar({ cost: ge(3), power: ge(7000) })), position: "top", faceUp: true }, power(upTo(1, myChar()), 2000, "until_start_of_your_next_turn")) }]),
  card("ST13-003", [{ trigger: "static", text: "Your face-up Life cards are placed at the bottom of your deck", statics: [{ s: "deck_rule", rule: "face_up_life_to_deck_bottom" }] }]),
  card("ST13-004", [{ trigger: "on_play", text: "[On Play] Add 1 card from the top of your deck to the top of your Life cards. Then, look at all",
    effect: seq({ do: "deck_to_life", player: "you", count: 1 }, { do: "look_life", player: "you", count: 99, rest: "any_order", prompt: "order your Life cards; the first card goes to the top of your deck" }, { do: "life_to_deck", player: "you", count: 1 }) }]),
  card("ST13-005", [{ trigger: "on_play", text: "[On Play] You may trash 1 card from the top or bottom of your Life cards",
    costs: [{ k: "trash_life", count: 1, position: "top_or_bottom" }],
    effect: { do: "hand_to_life", count: 1, min: 0, position: "top", faceUp: false, filter: { ...CHAR, cost: eq(5) } } }]),
  card("ST13-009", [{ trigger: "on_play", text: "[On Play] You may turn 1 of your face-up Life cards face-down",
    costs: [{ k: "life_face_down", count: 1, position: "any" }], effect: when(cmp({ count: { of: "hand", player: "opponent" } }, ">=", 7), { do: "trash_life", player: "opponent", count: 1 }) }]),
  card("ST13-016", [{ trigger: "on_play", text: "[On Play] Look at all your Life cards; place 1 at the top of your deck",
    effect: seq({ do: "look_life", player: "you", count: 99, rest: "any_order", prompt: "order your Life cards; the first card goes to the top of your deck" }, { do: "life_to_deck", player: "you", count: 1 }) }]),
  card("ST13-017", [{ trigger: "counter", text: "[Counter] Up to 1 of your Leader or Character cards gains +4000 power during this battle. Then, look at all",
    effect: seq(power(upTo(1, myLeaderOrChar()), 4000, "battle"), { do: "look_life", player: "you", count: 99, rest: "any_order" }) }]),
  card("ST17-005", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may place 1 card from your hand at the top of your deck",
    costs: [{ k: "hand_to_deck_top", count: 1 }], effect: { do: "give_don", target: exactly(1, myLeaderOrChar()), count: 2, donState: "rested" } }]),
  card("ST26-002", [{ trigger: "on_play", text: "[On Play] DON!! -2: Rest up to 1 of your opponent's DON!!", costs: [{ k: "return_don", count: 2 }], effect: rest(upTo(1, oppCharOrDon({ cost: le(1) }))) }]),
  card("ST28-004", [{ trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may return 2 total of your currently given DON!!",
    costs: [{ k: "unattach_don", count: 2 }], effect: seq(keyword(self, "rush"), power(self, 1000)) }]),
  card("ST30-016", [{ trigger: "counter", text: "[Counter] Up to 1 of your Leader or Character cards gains +3000 power during this battle. Then, if you have [Portgas.D.Ace]",
    effect: seq(power(upTo(1, myLeaderOrChar()), 3000, "battle"),
      when({ c: "and", conds: [exists(myChar({ names: ["Portgas.D.Ace"], basePower: eq(6000) })), exists(myChar({ names: ["Monkey.D.Luffy"], basePower: eq(6000) }))] }, draw(1))) }]),
  card("ST32-001", [{ trigger: "on_play", text: "[On Play] You may rest your <Slash> attribute Leader or 1 of your DON!!",
    costs: [{ k: "either", labels: ["Rest your <Slash> attribute Leader", "Rest 1 of your DON!! cards"], options: [[{ k: "rest_cards", selector: sel("you", "leader", { attributes: ["Slash"] }), count: 1 }], [{ k: "rest_don", count: 1 }]] }],
    effect: seq(draw(2), discard(1)) }]),
  card("ST33-004", [{ trigger: "static", text: "During the turn in which a card in your hand is trashed by an effect",
    conditions: [{ c: "this_turn", what: "hand_trashed", player: "you" }], statics: [{ s: "play_cost", target: "self", amount: -3 }] }]),
  card("ST36-005", [{ trigger: "on_opp_attack", oncePerTurn: true, text: "[On Your Opponent's Attack] [Once Per Turn] You may turn 1 card from the top or bottom",
    costs: [{ k: "life_face_down", count: 1, position: "top_or_bottom" }], effect: { do: "redirect_attack", target: exactly(1, myChar({ names: ["Eustass\"Captain\"Kid"], basePower: ge(5000) })) } },
    { trigger: "activate_main", oncePerTurn: true, text: "[Activate: Main] [Once Per Turn] You may turn 1 card from the top or bottom of your Life cards face-up",
      costs: [{ k: "life_face_up", count: 1, position: "top_or_bottom" }], effect: { do: "give_don", target: myLeader, count: 1, donState: "rested" } }]),
];

// Full replacement (the generated record dropped "and reveals their hand"): the opponent's remaining hand stays face up this turn (#491).
ENTRIES.push(["OP07-090", { abilities: [{ id: "op07-090#0", trigger: "on_play", text: "[On Play] Your opponent trashes 1 card from their hand and reveals their hand. Then, your opponent draws 1 card.",
  effect: seq({ do: "discard", player: "opponent", count: 1, chooser: "opponent" }, { do: "reveal", target: { ref: "all", selector: sel("opponent", "hand") } }, { do: "draw", player: "opponent", count: 1 }) }] }]);

export const MANUAL_ABILITIES: Record<string, ManualEntry> = Object.fromEntries(ENTRIES);
